### ISSUE TITLE
Problem with some messages.plain text

### ISSUE THREAD

**Issue by gonzupi** [jeremyephron/simple-gmail#10]
Hi, I love the project idea, it's great, but I'm having trouble with some messages because I can only access my content in HTML format. When I try to run the message.plain function, it just returns "none" and breaks my program (later) by throwing an exception when i try to acces the data because there is no string in there jajaja.

It seems that there is a difference between the messages that have been sent commonly and those sent from an automated service, since this is when it fails me, in the rest of the cases it works for me, in fact the rest of the fields do work well for me.

I'm going to copy the print(message.plain) and the print(message.html):
~~~
None
<body><p>ID Usuario: I1GW49XXTolXosysPDjxtGuqKgWl2 ||||||||| Nombre del documento: 6-15-08-2020:||||||||| GeometrÃ­a: I1GW49XXTolXosysPDjxtGuqKgWl2 _6_15-08-2020: ee.Geometry.MultiPolygon([[[[36.86925273034357,-4126351967930093],[36.73005241962277,-4.478030739902749],[36.73129063038372,-4.533649026035562]]]]),
</p></body>
~~~

Thnks for your attention!

**Comment by jeremyephron** [comment]
Hi @gonzupi, sorry to hear about your issue. Unfortunately, this is not a problem with the package that can be fixed. `Message.plain` is not guaranteed to exist for every message (neither is `Message.html`). These contents are determined when the email is created, and always  automatically done by the email service. When you create an email using the Gmail online client, for instance, both of these fields will be created. However, other automated services may not, as seems to be what you are experiencing.

There's no single, correct way to extract the "plain text" from HTML, so it's not something that should be built into this package. The plain field is populated by a component of the email message designated as "plain text", it's not inferred.

When using this package, always check for the case where `Message.plain` is `None` and you can look into using a package like `BeautifulSoup` to write something small to extract the "text" from the `html` field in that case.

I'm going to close this issue for now, but let me know if that addresses your concern!
