### ISSUE TITLE
Is it possible to save email attachment with a chosen/new file name?

### ISSUE THREAD

**Issue by mjuliefr** [jeremyephron/simple-gmail#11]
Hi 
Is it possible to save attachements with a different name than in the originating email, please ?
This is in case there are two unread emails and both have attachments with the same name. 
Kind regards,
Julie

**Comment by jeremyephron** [comment]
Yes, it is possible. This is the header for the `Attachment.save` function:

```python
def save(self, filepath=None, overwrite=False):
```

So you can pass in your desired filename as `filepath`. If you just pass in a name like `image.jpg` it will be saved in the current directory per usual, but you can also pass in a full path like `different/path/to/image.jpg`.

I'm working on writing more comprehensive documentation for the package as more people are using it, so info like this is more accessible. Hope this helps!

**Comment by mjuliefr** [comment]
Hi Jeremy, it does help. Thanks.
