### ISSUE TITLE
does it handle CLI tools authentification

### ISSUE THREAD

**Issue by mjuliefr** [jeremyephron/simple-gmail#12]
Hi,

I have a back end which will one gmail account to send email and retrieve unread attachment so I wonder if it does handle this kind of use case with a Cli tools type authentication  including the use of the refresh token avoiding the user need to log in, please?

Thanks Julie

**Comment by mjuliefr** [comment]
I have the code for the CLI tool authentication if needed.

**Comment by jeremyephron** [comment]
Hi @mjuliefr, can I see an example of what you want and what code you have?

**Comment by jeremyephron** [comment]
@mjuliefr Just wanted to let you know that you can authenticate once on your browser and then copy the "gmail_token.json" file to the new location to avoid having to log in again.

**Comment by mjuliefr** [comment]
Hi Jeremy thanks for the feedback,
