### ISSUE TITLE
circular import

### ISSUE THREAD

**Issue by illucent** [jeremyephron/simple-gmail#14]
Hi, have an issue, possible circular import with example "Retrieving messages (more advanced, with more queries!)". Thanks in advance.

```
python --version
Python 3.8.5
```
```
Traceback (most recent call last):
  File "/opt/scripts/gmail_analtycs/simplegmail.py", line 14, in <module>
    from simplegmail import Gmail
  File "/opt/scripts/gmail_analtycs/simplegmail.py", line 14, in <module>
    from simplegmail import Gmail
ImportError: cannot import name 'Gmail' from partially initialized module 'simplegmail' (most likely due to a circular import) (/opt/scripts/gmail_analtycs/simplegmail.py)
```

**Comment by jeremyephron** [comment]
Hi @illucent, this is not an issue with the simplegmail package but rather that your file is called "simplegmail.py", the same module name as the package. Inside of "simplegmail.py", when you try to import from `simplegmail` it thinks you are trying to import from "simplegmail.py" and not from the `simplegmail` package. Change the filename to fix the issue.

**Comment by illucent** [comment]
Works thanks, now I know what 'circular import' means. 👍🏻
