### ISSUE TITLE
Stuck at receiving mails

### ISSUE THREAD

**Issue by james1bb** [jeremyephron/simple-gmail#15]
Project Directory has both the files client_secret and gmail_token after printing done it just stuck their mail has like 200+- unread mails not sure what i am doing wrong.
```
from simplegmail import Gmail
gmail = Gmail()
print("done")
messages = gmail.get_unread_inbox()
print(messages[0])
```

**Comment by jeremyephron** [comment]
@james1bb How long did you wait? It can take a long time to receive the emails from Gmail. With 200 messages I would expect it to take around 45 seconds, if you have significantly more than 200, you could expect it to take longer.

**Comment by jeremyephron** [comment]
@james1bb To give you more insight: specifically, the thing that takes a long time is downloading the full content of each message, which is done one message at a time, sequentially (Google doesn't support any sort of batch request for the message contents).

In the near future I will add at least one the following different solutions to alleviate this problem:

- Sending each message request in parallel
- Downloading only the to, from, subject, and snippet fields for example, and letting the user specify when to download the rest of the message.

Let me know how you'd like to use the package!

**Comment by james1bb** [comment]
Yeah it worked it just too time I didn't waited long that was my mistake 😅😅 thanks for answering it.

**Comment by james1bb** [comment]
> @james1bb To give you more insight: specifically, the thing that takes a long time is downloading the full content of each message, which is done one message at a time, sequentially (Google doesn't support any sort of batch request for the message contents).
> 
> In the near future I will add at least one the following different solutions to alleviate this problem:
> 
> * Sending each message request in parallel
> * Downloading only the to, from, subject, and snippet fields for example, and letting the user specify when to download the rest of the message.
> 
> Let me know how you'd like to use the package!

For now everything needed is their in it I just want to fetch my mail body that's it and process it further with my code and save it.
Thanks
