### ISSUE TITLE
Authorised redirect URIs

### ISSUE THREAD

**Issue by cogency** [jeremyephron/simple-gmail#17]
Fantastic library @jeremyephron, thanks!

One difficulty - I kept getting invalid credentials errors from simple-gmail even though I had a valid json file. When creating the Google API credential you also have to specify an "Authorised redirect URI" for communicating back with the client, i.e.
http://localhost:8090/

Suggest adding this to your readme.md instructions for others.

best regards

**Comment by jeremyephron** [comment]
I haven't seen that one before. I will look into it and add the appropriate steps. Thanks for the suggestion!

**Comment by jeremyephron** [comment]
I added more information and a link to Google's page with the OAuth2.0 requirements for different kinds of applications.  Commit: 7cad7c12d6c1a4e606dda09635a85e7e1cd516a8
