### ISSUE TITLE
simple gmail & django

### ISSUE THREAD

**Issue by churongcon** [jeremyephron/simple-gmail#24]
Hello
I want to run simple gmail with django

```
gmail = Gmail(client_secret_file='/home/bank/html/client_secret.json',_creds='/home/bank/html/gmail_token.json')

AttributeError at /get/momo
'str' object has no attribute 'invalid'

```

how to add client secret file and _CREDENTIALS_FILE

**Comment by jeremyephron** [comment]
You should not use the `_creds` parameter, which exists for internal use only. You only use `client_secret_file`.

**Comment by churongcon** [comment]
EOF when reading a line

https://i.imgur.com/l6sha5o.png

It's still error

**Comment by jeremyephron** [comment]
Can you copy and paste the full error?

**Comment by churongcon** [comment]
https://bank.taikhoanykhoa.com/get/momo

@jeremyephron

**Comment by jeremyephron** [comment]
Can you copy and paste the contents of your client_secret.json file, but **replace all strings in the values with "..."**. Strings that are keys are fine, but make sure not to post any of the values publicly

**Comment by churongcon** [comment]
`{"installed":{"client_id":"xxx-xxx.apps.googleusercontent.com","project_id":"quickstart-1561091209545","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"xxx-SdJIyJ","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}`

**Comment by jeremyephron** [comment]
Okay I see why this is happening. It's from the step where typically it would launch a browser window to confirm authentication. If you want a quick fix, you can run
```
from simplegmail import Gmail
Gmail()
```
from a terminal window, which will launch a browser and request access. This will save a "gmail_token.json" file in the current directory. If you move that "gmail_token.json" file to the directory where the django server is being run, it should work.

I am working on an actual solution for this now, if you'd also like to wait.

**Comment by churongcon** [comment]
It is only working fine when run via terminal windows,

But in django, I need set path both client_secret_file and gmail_token file because It's django server can't detect path gmail_token.json

**Comment by churongcon** [comment]
Althought I have uploaded same folder but it can't detect gmail_token.json https://i.imgur.com/GiGop5r.png

**Comment by jeremyephron** [comment]
I see, you likely just need to move it to one of the inner folders where the script that's actually using `Gmail()` is located. Regardless, I just pushed a new version `3.1.3` which accepts a path to the credentials file:
```
gmail = Gmail(creds_file='/path/to/gmail_token.json')

**Comment by churongcon** [comment]
> ```
> gmail = Gmail(creds_file='/path/to/gmail_token.json')
> ```

Big thanks for your support.

Now It's working fine 💯

**Comment by jeremyephron** [comment]
Glad to hear it!
