### ISSUE TITLE
Passing user input to script

### ISSUE THREAD

**Issue by fox-ankii** [jeremyephron/simple-gmail#3]
Hello Jeremy,

First of all great work, i'm using your code to access gmail api I'm wondering if its possible if we can take recipient email from user and pass on that input into our code.

In your example where we define params, so can we pass a variable into it ?

Many Thanks in advance.

**Comment by jeremyephron** [comment]
Can you describe in more detail what you mean? Perhaps give an example of what it is you would like to do.

**Comment by fox-ankii** [comment]
Thank you for reply. Below is my code :-

Datetime2 is variable which havinf current date.
x is again a variable but I'm fetching it from database.
abc i've assigned a mail address.

So basically I wanted user to provide his/her mail address as well as the message they want in mail. So I got the way to take email address via variable abc.
But now how I can take HTML part from user. ??

while True :
 if datetime2 == x:
  params = {
  "to":   abc,
  "sender": "xxxx@gmail.com",
  "subject": yy,
  "msg_html": "<h1>Ankit is geneous!</h1><br />This is an HTML email.",
  "msg_plain": "Hi\nThis is a plain text email.",
  "signature": True  # use my account signature
 }
  message = gmail.send_message(**params)

**Comment by fox-ankii** [comment]
oops Please ignore my geneous reamrk :)

**Comment by jeremyephron** [comment]
This package allows you to pass in whatever HTML message you'd like. It seems like your question is about how to get user input, which would not be a part of this package. It's up to you how you want to do that.

You could, most simply just write something like:
```
msg_html = input('Enter you HTML message here: ')
>>> <h1> Welcome! <h1> <br/> <p>Hi there, my name is... </p>

params = {
    ...,
    "msg_html": msg_html,
    ...
}
message = gmail.send_message(**params)
```

where ">>>" denotes that the user is typing the text on that line.

**Comment by fox-ankii** [comment]
Thank you for your reply. I too had thought in same way but as per understanding msg_html will contain only user provided data so how it could be embed with html code.

msg_html = input('Enter you HTML message here: ') ---- This is for user input code
>>> <h1> Welcome! <h1> <br/> <p>Hi there, my name is... </p>---- This is for html code

so how to embed both code so it can be pass further as a single message.

Hope I'm able to convey my message. Appologies if its a silly question.
