### ISSUE TITLE
Installation and basic Connection

### ISSUE THREAD

**Issue by Btibert3** [jeremyephron/simple-gmail#4]
I want to kick the tires of this package, as this is **exactly** what I was looking for, but I ran into a few issues.

For context, I am running on Colab.  Notebook and output here: https://colab.research.google.com/drive/1Y8Le95TLcVu3GR3IsiySa8l-MOJ7nNyj

1.  `pip3` and `pip` install didn't work, so I had to clone the repo to install
1.  `gmail = Gmail()` failed 

Just wanted to share, but admit it could be related to using the Colab environment, though I generally haven't had issues in the past.

**Comment by jeremyephron** [comment]
To address the first issue, the package is certainly on PyPi, so `pip3 install simplegmail` should work in all environments you would expect it to.

Second, the first time you create a new instance of the `Gmail` class, (`gmail = Gmail()`), a browser window is opened to confirm permissions for your Google account.

I suspect that both of these issues are related to the Colab environment. I will try to look into what can be done with regard to that. If you have any suggestions, feel free to post them here.
