### ISSUE TITLE
Disable cache

### ISSUE THREAD

**Issue by pierre-24** [jeremyephron/simple-gmail#6]
When using the code, I get the (non-blocking) error `ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth`. According to [StackOverflow](https://stackoverflow.com/questions/40154672/importerror-file-cache-is-unavailable-when-using-python-client-for-google-ser), the trick is simply to add `cache_discovery=False` to the `build()` function  [there](https://github.com/jeremyephron/simple-gmail/blob/master/simplegmail/gmail.py#L72) :)

**Comment by jeremyephron** [comment]
Hi, I wasn't able to reproduce this error on my own machine. Can you detail the steps to reproduce? Also what is the downside of disabling the cache here?

**Comment by pierre-24** [comment]
I know why it shows up:

```python
ìmport logging
logging.basicConfig(level='INFO')
import simplegmail

g = simplegmail.Gmail()
g.send_message(to='****@gmail.com', sender=***@gmail.com', subject='test',msg_plain='test', msg_html='<i>test</i>')
```

... Because I set the log output to `INFO` ;)

But removing the cache seems to be [Google's decision](https://github.com/googleapis/google-api-python-client/issues/325), so it seems ok to keep it like this, I'll just have a weird warning showing up in my log from time to time!

```

**Comment by jeremyephron** [comment]
Just to confirm my understanding: not having `cache_discovery=False` will do absolutely nothing because of this error, correct? If that's the case, then I will add it, I just wanted to make sure I wasn't disabling any behavior unwittingly.

**Comment by pierre-24** [comment]
Yes, that seems to be it :)

**Comment by jeremyephron** [comment]
Okay, `cache_discovery=False` has been added as an argument to build per your suggestion.

**Comment by pierre-24** [comment]
Thanks for all those improvements ;)
