### ISSUE TITLE
Move e-mail

### ISSUE THREAD

**Issue by rodolfonobrega** [jeremyephron/simple-gmail#8]
Is it possible to create a method that moves the e-mail to another folder?

It would be useful, for example, when you want to make a program that downloads attachments and you want to move the e-mails that you have already downloaded the attachments to another folder.

Thanks in advance and congrats for your great job.

**Comment by jeremyephron** [comment]
Thanks for the suggestion, I will look into this when I get the opportunity; should be doable.

**Comment by jeremyephron** [comment]
Hi @rodolfonobrega, I added a `Gmail.list_labels` function to grab your account's labels, and now you can use the existing `Message.modify_labels` to add one label and remove another (which is all moving does). There also is a `Message.move_from_inbox` function for convenience if the label you are removing is your inbox.

Check out [this simple example](https://github.com/jeremyephron/simple-gmail/blob/master/README.md#changing-message-labels) in the README, and check out [message.py](https://github.com/jeremyephron/simple-gmail/blob/master/simplegmail/message.py).
