### ISSUE TITLE
Look into improving efficiency, and/or add support for paging if appropriate

### ISSUE THREAD

**Issue by jeremyephron** [jeremyephron/simple-gmail#9]
For big inboxes, it can take a very long time to pull all the messages. It's worthwhile to looking into faster ways of accomplishing this or exposing an API for paging or async.

**Comment by jamesmalin** [comment]
Cool - are you still looking into this?

Btw, great library. Thanks.

**Comment by jeremyephron** [comment]
@jamesmalin Yes, I am. I actually just implemented a multithreaded version on my end which seems to be successful.

I just need to think through 
- whether I want to have this parallelization by default or be explicitly requested;
- whether I want to generate the new Gmail connections required for the parallelization at init of the `Gmail` object or at the point of downloading the messages
- whether to also expose APIs for downloading full messages after the fact (so initially only downloading select fields)

I tend to lean toward the side of not doing too much without prior knowledge that there are users who want this. Any thoughts, questions, concerns, or use cases?

**Comment by jeremyephron** [comment]
Update: I've had multithreaded email downloads working awhile back with great speedup, but somewhere down the line of bs4 parsing the html from the emails an error message is printed when processing on multiple threads that I have not been able to get to the bottom of or silence, which is preventing it from being rolled out.

**Comment by roib20** [comment]
Glad to hear you're making progress. A faster simplegmail would be amazing, thank you for your work.

**Comment by jamesmalin** [comment]
@jeremyephron It's been working well without multithread. I have been marking as read for each email I extract the attach for, so I also put the filter to only go back 1 day. I run this with a cronjob twice a day just to make sure I didn't miss anything.

I have tested, but when filtering with the above example it isn't grabbing all contents of the inbox correct? In this example, it's just going back one day - is that right?

Thank you for working on this. I use your library for several companies.

**Comment by jeremyephron** [comment]
@jamesmalin Glad to hear it. Using `'newer_than': (1, 'day')` like in the example [here](https://github.com/jeremyephron/simple-gmail#retrieving-messages-advanced-with-queries) will only return messages received within the past 24 hours. Extra filters can be added on top of any of the convenience functions by passing in the right parameters. So yes, if that's what you're doing, that should be correct.

Filtering is indeed a great way to improve performance. I hope to add multithreaded support soon because there's no reason not to, but unfortunately I will need to replace one of the package's dependencies in order to do so.

**Comment by jamesmalin** [comment]
@jeremyephron Yes, I am using a few of the different filters you added. I'll test it out when you're ready.

**Comment by jeremyephron** [comment]
@jamesmalin multithreaded download has been added (ended up fixing the problem with bs4). It should be significantly faster now. On my regular old 4-core laptop, it takes about 12 seconds for 420 messages (whereas before it was about 12 seconds for 50 messages). The newest version 3.1.0 is downloadable with pip as usual.
